# Generated by Django 3.0.5 on 2020-09-30 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('constant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hesap Adı')),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hesap No')),
                ('iban', models.CharField(blank=True, max_length=26, null=True, verbose_name='IBAN')),
                ('internet_pass', models.CharField(blank=True, max_length=20, null=True, verbose_name='İnternet Şifresi')),
                ('mobile_pass', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobil Şifresi')),
                ('cart_no', models.CharField(blank=True, max_length=26, null=True, verbose_name='Kart Numarası')),
                ('last_month', models.CharField(blank=True, max_length=2, null=True, verbose_name='Son Kullanım Ayı')),
                ('last_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Son Kullanım Tarihi')),
                ('csv', models.CharField(blank=True, max_length=3, null=True, verbose_name='CSV')),
                ('card_pass', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kart Şifresi')),
                ('secret_phrase', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gizli Kelime')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('update_date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Güncelleme Tarihi')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Miktar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('card_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CardTypeLM', verbose_name='Kart Tipi')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CorporationLM', verbose_name='Bankası')),
            ],
            options={
                'db_table': 'account_m',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Para Birimi')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sembolü')),
                ('rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Endeksi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'currency_m',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Tarih')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Saat')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Miktar')),
                ('account_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Hesap Miktarı')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.Account', verbose_name='Hesap')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.TransactionCategoryLM', verbose_name='İşlem Kategorisi')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CorporationLM', verbose_name='İşlem Yeri')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.TransactionTypeLM', verbose_name='İşlem Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'transaction_m',
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Tarih')),
                ('start_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Başlama Oranı')),
                ('end_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bitme Oranı')),
                ('max_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='En Fazla Oran')),
                ('min_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='En Az Oran')),
                ('avg_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ortalama Oran')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.Currency', verbose_name='Para Birimi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'currencyhistory_m',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Kime - Kimden')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.ChangePurposeLM', verbose_name='Aldım - Verdim Amacı')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.Transaction', verbose_name='İşlem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'change_m',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.Currency', verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Sahibi'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
