# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['corporation', 'name']},
        ),
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['is_active']},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='currencyhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-time']},
        ),
    ]
