# Generated by Django 3.1.2 on 2020-10-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20201007_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='place',
            new_name='corporation',
        ),
    ]
