# Generated by Django 3.1.2 on 2020-11-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0003_auto_20201018_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-is_active']},
        ),
        migrations.AddField(
            model_name='change',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AddField(
            model_name='change',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı'),
        ),
        migrations.CreateModel(
            name='ChangeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.change', verbose_name='Aldım - Verdim')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.transaction', verbose_name='İşlem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'change_transaction_m',
                'ordering': ['change'],
            },
        ),
    ]
