# Generated by Django 3.1.2 on 2020-11-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_auto_20201107_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='transaction',
        ),
    ]
