# Generated by Django 3.1.2 on 2020-11-15 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_change_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['name', '-is_active']},
        ),
        migrations.AddField(
            model_name='change',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Ekleme Tarihi'),
        ),
    ]
