# Generated by Django 3.1.2 on 2020-11-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_auto_20201115_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-is_active', '-date']},
        ),
    ]
