# Generated by Django 3.1.2 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_auto_20201129_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='change',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='changetransaction',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
