# Generated by Django 3.1.2 on 2021-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_auto_20210103_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='change',
            name='user',
        ),
        migrations.RemoveField(
            model_name='changetransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
