# Generated by Django 3.0.5 on 2020-09-30 18:52

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Türü')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Başlık')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
            ],
            options={
                'db_table': 'panel_lm',
            },
        ),
        migrations.CreateModel(
            name='SchoolLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Okul Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CityLM', verbose_name='İli')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.SchoolTypeLM', verbose_name='Okul Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'school_lm',
            },
        ),
        migrations.CreateModel(
            name='PersonGroupLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'persongroup_lm',
            },
        ),
        migrations.CreateModel(
            name='PathLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('path', models.CharField(blank=True, max_length=100, null=True, verbose_name='Güzergah')),
                ('view_func', models.CharField(blank=True, max_length=100, null=True, verbose_name='View Fonksiyonu')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Açıklama')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Konumu')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.PanelLM', verbose_name='Panel')),
            ],
            options={
                'db_table': 'path_lm',
            },
        ),
        migrations.CreateModel(
            name='ModelLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model Adı')),
                ('db_table', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tablo Adı')),
                ('list_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Liste Başlığı')),
                ('form_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Form Başlığı')),
                ('detail_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detay Başlığı')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Açıklaması')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.PanelLM', verbose_name='Panel Adı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'model_lnm',
            },
        ),
        migrations.CreateModel(
            name='FieldLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sıra No')),
                ('field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alan Türü')),
                ('null', models.BooleanField(default=True, verbose_name='Null ?')),
                ('blank', models.BooleanField(default=True, verbose_name='Blank ?')),
                ('max_length', models.CharField(blank=True, max_length=50, null=True, verbose_name='En Fazla Uzunluk')),
                ('on_delete', models.CharField(blank=True, max_length=100, null=True, verbose_name='Silinme Şekli')),
                ('to', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlişkili Tablo')),
                ('default', models.CharField(blank=True, max_length=100, null=True, verbose_name='Varsayılan Değer')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alan Başlığı')),
                ('max_digits', models.CharField(blank=True, max_length=50, null=True, verbose_name='En Fazla Hane')),
                ('decimal_places', models.CharField(blank=True, default=3, max_length=50, null=True, verbose_name='Virgülden sonraki hane')),
                ('format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Format')),
                ('show_list', models.BooleanField(default=True, verbose_name='Listede Gösterimi')),
                ('form', models.CharField(blank=True, max_length=50, null=True, verbose_name='Form Özelliği')),
                ('form_add', models.BooleanField(default=True, verbose_name='Eklenebilir')),
                ('form_delete', models.BooleanField(default=True, verbose_name='Silinebilir')),
                ('form_update', models.BooleanField(default=True, verbose_name='Değiştirilebilir')),
                ('show_detail', models.BooleanField(default=True, verbose_name='Detayda Gösterimi')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ModelLM', verbose_name='Model Adı')),
            ],
            options={
                'db_table': 'field_lm',
            },
        ),
        migrations.CreateModel(
            name='DepartmentLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'department_lm',
            },
        ),
        migrations.CreateModel(
            name='CorporationLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Firma Adı')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Eklenme Tarihi')),
                ('web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Web Adresi')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CityLM', verbose_name='İli')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.MarketLM', verbose_name='Market Tipi')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.TownLM', verbose_name='İlçesi')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CorporationTypeLM', verbose_name='Firma Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'corporation_lm',
            },
        ),
    ]
