# Generated by Django 3.0.5 on 2020-10-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modellm',
            table='model_lm',
        ),
    ]
