# Generated by Django 3.0.5 on 2020-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201003_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellm',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sıra No'),
        ),
    ]
