# Generated by Django 3.0.5 on 2020-10-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_modellm_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellm',
            name='user',
        ),
    ]
