# Generated by Django 3.0.5 on 2020-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_modellm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldlm',
            name='format',
        ),
        migrations.AddField(
            model_name='fieldlm',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı'),
        ),
    ]
