# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201004_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporationlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='departmentlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fieldlm',
            options={'ordering': ['model', 'order']},
        ),
        migrations.AlterModelOptions(
            name='modellm',
            options={'ordering': ['panel', 'order']},
        ),
        migrations.AlterModelOptions(
            name='panellm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pathlm',
            options={'ordering': ['panel', 'name']},
        ),
        migrations.AlterModelOptions(
            name='schoollm',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AddField(
            model_name='modellm',
            name='ordering',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sıralama'),
        ),
    ]
