# Generated by Django 3.0.5 on 2020-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201007_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldlm',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sıra No'),
        ),
        migrations.AlterField(
            model_name='modellm',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sıra No'),
        ),
    ]
