# Generated by Django 3.1.2 on 2020-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201007_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathlm',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='pathlm',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Türü'),
        ),
    ]
