# Generated by Django 3.1.2 on 2020-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201018_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldlm',
            name='max_digits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='En Fazla Basamak'),
        ),
        migrations.AlterField(
            model_name='fieldlm',
            name='max_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='En Fazla Karakter'),
        ),
    ]
