# Generated by Django 3.1.2 on 2020-11-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201107_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldlm',
            name='decimal_places',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Virgülden sonraki hane'),
        ),
    ]
