# Generated by Django 3.1.2 on 2020-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201115_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellm',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='modellm',
            name='verbose_name_plural',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Çoğul Başlık'),
        ),
        migrations.AlterField(
            model_name='modellm',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması'),
        ),
    ]
