# Generated by Django 3.1.4 on 2020-12-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201129_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldlm',
            old_name='form_update',
            new_name='form_updatee',
        ),
    ]
