# Generated by Django 3.1.4 on 2020-12-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201212_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldlm',
            old_name='form_updatee',
            new_name='form_update',
        ),
    ]
