# Generated by Django 3.1.2 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201212_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationlm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='departmentlm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='modellm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='panellm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='pathlm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='persongrouplm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='schoollm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
