# Generated by Django 3.1.2 on 2021-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210103_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathlm',
            name='desc',
            field=models.CharField(blank=True, default='olalal', max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
