# Generated by Django 3.1.2 on 2021-01-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210110_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathlm',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
