# Generated by Django 3.1.2 on 2021-03-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0003_auto_20210103_1239'),
        ('main', '0016_auto_20210112_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporationlm',
            name='type',
        ),
        migrations.AddField(
            model_name='corporationlm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.transactioncategorylm', verbose_name='Firma Kategorisi'),
        ),
    ]
