# Generated by Django 3.1.2 on 2021-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210314_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporationlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='departmentlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='persongrouplm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schoollm',
            name='user',
        ),
    ]
