# Generated by Django 3.0.5 on 2020-09-30 18:53

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uygulama Adı')),
                ('web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Web Adresi')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanıcı Adı')),
                ('backup_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Yedek E-Mail Adresi')),
                ('pass1', models.CharField(blank=True, max_length=20, null=True, verbose_name='1. Şifre')),
                ('pass2', models.CharField(blank=True, max_length=20, null=True, verbose_name='2. Şifre')),
                ('secret_phrase', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gizli Kelime')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('update_date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Güncelleme Tarihi')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.PersonEmail', verbose_name='E-Mail Adresi')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Sahibi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'mypassword_m',
            },
        ),
    ]
