# Generated by Django 3.1.2 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201007_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypassword',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
