# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylog',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='mygroup',
            options={'ordering': ['corporation', 'name']},
        ),
        migrations.AlterModelOptions(
            name='personalpermission',
            options={'ordering': ['user', 'model', 'ability']},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelTable(
            name='myuserprofile',
            table=None,
        ),
    ]
