# Generated by Django 3.1.2 on 2020-11-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('authentication', '0002_auto_20201007_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historylog',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='historylog',
            name='model',
        ),
        migrations.AddField(
            model_name='historylog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session', verbose_name='Session'),
        ),
    ]
