# Generated by Django 3.1.2 on 2020-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201107_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylog',
            name='csrftoken',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Csrf Token'),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oturum Kodu'),
        ),
    ]
