# Generated by Django 3.1.2 on 2020-11-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_auto_20201107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Adresi'),
        ),
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ip Adresi')),
                ('permission', models.BooleanField(blank=True, default=True, null=True, verbose_name='Yetki')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'user_ip',
                'ordering': ['user', 'ip'],
            },
        ),
    ]
