# Generated by Django 3.1.2 on 2020-11-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201107_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='permission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yetki'),
        ),
    ]
