# Generated by Django 3.1.4 on 2020-12-12 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_auto_20201115_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalpermission',
            options={'ordering': ['user', 'model']},
        ),
        migrations.RemoveField(
            model_name='personalpermission',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='personalpermission',
            name='id_no',
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('personal_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.personalpermission', verbose_name='Kişisel İzinler')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'user_permission',
                'ordering': ['user', 'personal_permission'],
            },
        ),
    ]
