# Generated by Django 3.1.4 on 2020-12-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201212_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalpermission',
            options={'ordering': ['user_name', 'model']},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterModelOptions(
            name='userip',
            options={'ordering': ['user_name', 'ip']},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'ordering': ['user_name', 'personal_permission']},
        ),
        migrations.RenameField(
            model_name='historylog',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='personalpermission',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userip',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='user',
            new_name='user_name',
        ),
    ]
