# Generated by Django 3.1.2 on 2021-01-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210103_1239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personalpermission',
            table='model_permission',
        ),
    ]
