# Generated by Django 3.1.2 on 2021-01-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210116_2331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personalpermission',
            table='temp_table',
        ),
    ]
