# Generated by Django 3.1.2 on 2021-01-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_modelpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='personal_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.modelpermission', verbose_name='Kişisel İzinler'),
        ),
    ]
