# Generated by Django 3.1.2 on 2021-01-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210116_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalPermission',
        ),
    ]
