# Generated by Django 3.1.2 on 2021-01-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210112_2320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0014_delete_personalpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpermission',
            options={'ordering': ['user', 'model']},
        ),
        migrations.RenameField(
            model_name='modelpermission',
            old_name='user_name',
            new_name='user',
        ),
        migrations.CreateModel(
            name='PathPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pathlm', verbose_name='Model Adı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'path_permission',
                'ordering': ['user', 'path'],
            },
        ),
        migrations.CreateModel(
            name='PanelPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.panellm', verbose_name='Panel Adı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'panel_permission',
                'ordering': ['user', 'panel'],
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modellm', verbose_name='Model Adı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'field_permission',
                'ordering': ['user', 'field'],
            },
        ),
    ]
