# Generated by Django 3.1.2 on 2021-01-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20210117_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usergroup', verbose_name='Grup'),
        ),
        migrations.AddField(
            model_name='modelpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usergroup', verbose_name='Grup'),
        ),
        migrations.AddField(
            model_name='panelpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usergroup', verbose_name='Grup'),
        ),
        migrations.AddField(
            model_name='pathpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usergroup', verbose_name='Grup'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usergroup', verbose_name='Grup'),
        ),
    ]
