# Generated by Django 3.1.2 on 2021-01-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210112_2320'),
        ('authentication', '0017_auto_20210117_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modellm', verbose_name='Model Alanı Adı'),
        ),
        migrations.AlterField(
            model_name='pathpermission',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pathlm', verbose_name='Güzergah Adı'),
        ),
    ]
