# Generated by Django 3.1.2 on 2021-02-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20210117_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.mygroup', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='modelpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.mygroup', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='panelpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.mygroup', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='pathpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.mygroup', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.mygroup', verbose_name='Grup'),
        ),
    ]
