# Generated by Django 3.1.6 on 2021-02-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210112_2320'),
        ('authentication', '0019_auto_20210222_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fieldlm', verbose_name='Model Alanı Adı'),
        ),
    ]
