# Generated by Django 3.1.6 on 2021-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20210225_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldpermission',
            name='permission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yetki'),
        ),
        migrations.AddField(
            model_name='modelpermission',
            name='permission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yetki'),
        ),
        migrations.AddField(
            model_name='panelpermission',
            name='permission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yetki'),
        ),
        migrations.AddField(
            model_name='pathpermission',
            name='permission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yetki'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yetki'),
        ),
    ]
