# Generated by Django 3.1.4 on 2021-02-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20210225_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldpermission',
            options={'ordering': ['user_name', 'field']},
        ),
        migrations.AlterModelOptions(
            name='modelpermission',
            options={'ordering': ['user_name', 'model']},
        ),
        migrations.AlterModelOptions(
            name='panelpermission',
            options={'ordering': ['user_name', 'panel']},
        ),
        migrations.AlterModelOptions(
            name='pathpermission',
            options={'ordering': ['user_name', 'path']},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['group', 'user_name']},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'ordering': ['user_name', 'model_permission']},
        ),
        migrations.RenameField(
            model_name='fieldpermission',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='modelpermission',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='panelpermission',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='pathpermission',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='personal_permission',
            new_name='model_permission',
        ),
    ]
