# Generated by Django 3.0.5 on 2020-09-30 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constant', '0001_initial'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('period_amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Periyot Miktarı')),
                ('id_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hesap No')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kısa Kod')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CorporationLM', verbose_name='Firma')),
                ('period_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.PeriodLM', verbose_name='Periyot Sıkılığı')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Sahibi')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.RepetitiveTypeLM', verbose_name='Tekrarlı Olay Türü')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'repetitive',
            },
        ),
        migrations.CreateModel(
            name='RepetitiveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Son Ödeme Tarihi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('repetitive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarr.Repetitive', verbose_name='Tekrarlı Olay')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.Transaction', verbose_name='İşlem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'repetitive_record',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Tarih')),
                ('time', models.TimeField(blank=True, max_length=5, null=True, verbose_name='Saat')),
                ('duration', models.CharField(blank=True, max_length=5, null=True, verbose_name='Süre')),
                ('loc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Konum')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.EventTypeLM', verbose_name='Etkinlik Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'event_m',
            },
        ),
    ]
