# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='repetitive',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='repetitiverecord',
            options={'ordering': ['-last_date']},
        ),
    ]
