# Generated by Django 3.1.2 on 2020-10-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarr', '0002_auto_20201007_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repetitiverecord',
            options={'ordering': ['-transaction', 'last_date']},
        ),
        migrations.AddField(
            model_name='repetitiverecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi?'),
        ),
    ]
