# Generated by Django 3.1.2 on 2020-10-31 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20201018_2126'),
        ('calendarr', '0003_auto_20201030_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repetitiverecord',
            options={'ordering': ['-is_active', 'last_date']},
        ),
        migrations.AddField(
            model_name='repetitive',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.change', verbose_name='Aldım - Verdim'),
        ),
    ]
