# Generated by Django 3.1.2 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarr', '0004_auto_20201101_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='repetitiverecord',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
