# Generated by Django 3.1.2 on 2021-02-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarr', '0005_auto_20210103_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repetitiverecord',
            options={'ordering': ['-is_active', '-last_date']},
        ),
        migrations.AddField(
            model_name='repetitiverecord',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Miktar'),
        ),
    ]
