# Generated by Django 3.1.2 on 2021-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarr', '0006_auto_20210205_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetitive',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repetitiverecord',
            name='user',
        ),
    ]
