"""
Django settings for myERP project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p1ow&mf$l-$2l6o@#-&8vt7^gd%pqqv^-#9^z(!$n=)87fpnd%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["talhacelik.com","myerp.talhacelik.com","127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication.apps.AuthenticationConfig',
    'calendarr.apps.CalendarrConfig',
    'financial.apps.FinancialConfig',
    'main.apps.MainConfig',
    'note.apps.NoteConfig',
    'people.apps.PeopleConfig',
    'series.apps.SeriesConfig',
    'constant.apps.ConstantConfig',
    'demo.apps.DemoConfig',
    'tempus_dominus',
    # 'django_request_logging-0.7.2.dist-info',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'user_visit.middleware.UserVisitMiddleware',
    #'request_logging.middleware.LoggingMiddleware',
    'functions.logger.RequestMessageMiddleware',
]

ROOT_URLCONF = 'myERP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'template_funcs': 'functions.template_funcs'
            }
        },
    },
]

WSGI_APPLICATION = 'myERP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'myerp',
#         'USER': 'root',
#         'PASSWORD': 'Tlhclk.13',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "myerp.talhacelik.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "admin@myerp.talhacelik.com"
EMAIL_HOST_PASSWORD = "Hobula.5357"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USER_SSL = True
EMAIL_USER_TLS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'templates/bootstrap'), ]
STATIC_ROOT = os.path.join(BASE_DIR, '../static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = 'home'
LOGOUT_URL = 'logout'
#TEMPUS_DOMINUS_LOCALIZE = True

import datetime
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': 'levelname:%(levelname)s_asctime:%(asctime)s_created:%(created)f_filename:%(filename)s_funcName:%(funcName)s_levelno:%(levelno)s_lineno:%(lineno)d_module:%(module)s_msecs:%(msecs)d_message:%(message)s_name:%(name)s_pathname:%(pathname)s_process:%(process)d_processName:%(processName)s_relativeCreated:%(relativeCreated)d_thread:%(thread)d_threadName:%(threadName)s_'
        },
        'simple': {
            'format': '%(levelname)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.getcwd()+'/logger/logger_%s.log' % (datetime.datetime.now().strftime("%Y-%m-%d")),
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django':{
            'handlers':['console', 'file'],
            'level':'INFO',
            'propagate': False,
        },
    }
}
