# Generated by Django 3.0.5 on 2020-09-30 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('constant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Kişi Kodu')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tam Adı')),
                ('id_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Kimlik Numarası')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlk Adı')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkinci Adı')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ek Adı')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyadı')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Takma Adı')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ünvanı')),
                ('dateofbirth', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Doğum Tarihi')),
                ('hometown', models.CharField(blank=True, max_length=50, null=True, verbose_name='Memleketi')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresi')),
                ('dateofdeath', models.DateField(blank=True, null=True, verbose_name='Ölüm Tarihi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CityLM', verbose_name='İli')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CountryLM', verbose_name='Ülkesi')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.GenderLM', verbose_name='Cinsiyeti')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.PersonGroupLM', verbose_name='Grubu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'person_m',
            },
        ),
        migrations.CreateModel(
            name='RelationTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kişi 1')),
                ('person2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kişi 2')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.RelationshipLM', verbose_name='İlişki')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'relationtree_m',
            },
        ),
        migrations.CreateModel(
            name='PersonSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanıcı Adı')),
                ('web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('media_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.MediaTypeLM', verbose_name='Sosyal Medya Tipi')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Kimin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'personsocial_m',
            },
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('web_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fotoğraf Adresi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Kimin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'personphoto_m',
            },
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Kimin')),
                ('phone_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.PhoneTypeLM', verbose_name='Telefon Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'personphone_m',
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-Mail Adresi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('email_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.EmailTypeLM', verbose_name='E-Mail Tipi')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Kimin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'personemail_m',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Mezuniyet Yılı')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DepartmentLM', verbose_name='Bölümü')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person', verbose_name='Kim')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SchoolLM', verbose_name='Okul')),
                ('school_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.SchoolTypeLM', verbose_name='Okul Tipi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'education_m',
            },
        ),
    ]
