# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='personemail',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='personphone',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='personsocial',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='relationtree',
            options={'ordering': ['person1', 'person2']},
        ),
    ]
