# Generated by Django 3.1.2 on 2020-10-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201007_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='relations',
            field=models.ManyToManyField(blank=True, to='people.RelationTree', verbose_name='İlişkileri'),
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='person1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='people.person', verbose_name='Kişi 1'),
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_person', to='people.person', verbose_name='Kişi 2'),
        ),
    ]
