# Generated by Django 3.1.2 on 2020-10-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201023_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='relations',
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='person1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kişi 1'),
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='person2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kişi 2'),
        ),
    ]
