# Generated by Django 3.1.2 on 2020-10-22 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0004_auto_20201023_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationtree',
            options={'ordering': ['person', 'relation']},
        ),
        migrations.RemoveField(
            model_name='relationtree',
            name='person1',
        ),
        migrations.RemoveField(
            model_name='relationtree',
            name='person2',
        ),
        migrations.AddField(
            model_name='relationtree',
            name='person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kişi'),
        ),
        migrations.CreateModel(
            name='RelationTreePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kişi')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('relation_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.relationtree', verbose_name='İlişki Ağacı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'relationtree_person',
                'ordering': ['person', 'relation_tree'],
            },
        ),
    ]
