# Generated by Django 3.1.2 on 2020-10-22 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20201023_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtree',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Kişi'),
        ),
        migrations.AlterField(
            model_name='relationtreeperson',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Kişi'),
        ),
    ]
