# Generated by Django 3.1.2 on 2021-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20201023_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='personphone',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='personsocial',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
        migrations.AlterField(
            model_name='relationtreeperson',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması'),
        ),
    ]
