# Generated by Django 3.1.2 on 2021-04-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_remove_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personemail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personphone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personphoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personsocial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationtree',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationtreeperson',
            name='user',
        ),
    ]
