# Generated by Django 3.0.5 on 2020-09-30 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ana Seri Adı')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seri Adı')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkincil Adı')),
                ('web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Web Adresi')),
                ('rate', models.CharField(blank=True, max_length=5, null=True, verbose_name='Puanı')),
                ('current_eps', models.CharField(blank=True, max_length=3, null=True, verbose_name='Mevcut Bölüm')),
                ('total_eps', models.CharField(blank=True, max_length=3, null=True, verbose_name='Toplam Bölüm')),
                ('season', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sezon Adedi')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Başlama Tarihi')),
                ('director', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yönetmeni')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CountryLM', verbose_name='Ülkesi')),
                ('download', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.SeriesDownloadLM', verbose_name='İndirilebilirliği')),
                ('series_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.SeriesTypeLM', verbose_name='Seri Tipi')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.SeriesStateLM', verbose_name='Durumu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'series_m',
            },
        ),
        migrations.CreateModel(
            name='SeriesGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.SeriesGenreLM', verbose_name='Seri Türü')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.Series', verbose_name='Seri')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'seriesgenre_m',
            },
        ),
        migrations.CreateModel(
            name='RelatedSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seri 1')),
                ('series2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seri 2')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'relatedseries_m',
            },
        ),
    ]
