# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedseries',
            options={'ordering': ['series1', 'series2']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name', 'season', 'current_eps']},
        ),
        migrations.AlterModelOptions(
            name='seriesgenre',
            options={'ordering': ['series']},
        ),
    ]
