# Generated by Django 3.1.2 on 2021-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20210103_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedseries',
            name='user',
        ),
        migrations.RemoveField(
            model_name='series',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seriesgenre',
            name='user',
        ),
    ]
