# Generated by Django 3.0.5 on 2020-09-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
            ],
            options={
                'db_table': 'city_lm',
            },
        ),
        migrations.CreateModel(
            name='ContinentLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'continent_lm',
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'transactiontype_lm',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategoryLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'transactioncategory_lm',
            },
        ),
        migrations.CreateModel(
            name='TownLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CityLM', verbose_name='İli')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'town_lm',
            },
        ),
        migrations.CreateModel(
            name='SeriesTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'seriestype_lm',
            },
        ),
        migrations.CreateModel(
            name='SeriesStateLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'seriesstate_lm',
            },
        ),
        migrations.CreateModel(
            name='SeriesGenreLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'seriesgenre_lm',
            },
        ),
        migrations.CreateModel(
            name='SeriesDownloadLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'seriesdownload_lm',
            },
        ),
        migrations.CreateModel(
            name='SchoolTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'schooltype_lm',
            },
        ),
        migrations.CreateModel(
            name='RepetitiveTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'repetitivetype_lm',
            },
        ),
        migrations.CreateModel(
            name='RelationshipLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'relationship_lm',
            },
        ),
        migrations.CreateModel(
            name='PhoneTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'phonetype_lm',
            },
        ),
        migrations.CreateModel(
            name='PeriodLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('day', models.CharField(blank=True, max_length=4, null=True, verbose_name='Gün')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'period_lm',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('base_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kaynak Url')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'mediatype_lm',
            },
        ),
        migrations.CreateModel(
            name='MarketLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'market_lm',
            },
        ),
        migrations.CreateModel(
            name='GenderLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'gender_lm',
            },
        ),
        migrations.CreateModel(
            name='EventTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'eventtype_lm',
            },
        ),
        migrations.CreateModel(
            name='EmailTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'emailtype_lm',
            },
        ),
        migrations.CreateModel(
            name='CountryLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.ContinentLM', verbose_name='Kıtası')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'country_lm',
            },
        ),
        migrations.CreateModel(
            name='CorporationTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'corporationtype_lm',
            },
        ),
        migrations.AddField(
            model_name='citylm',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constant.CountryLM', verbose_name='Ülkesi'),
        ),
        migrations.AddField(
            model_name='citylm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='ChangePurposeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'changepurpose_lm',
            },
        ),
        migrations.CreateModel(
            name='CardTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklaması')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'db_table': 'cardtype_lm',
            },
        ),
    ]
