# Generated by Django 3.0.5 on 2020-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='changepurposelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='citylm',
            options={'ordering': ['country', 'name']},
        ),
        migrations.AlterModelOptions(
            name='continentlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='corporationtypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='countrylm',
            options={'ordering': ['continent', 'name']},
        ),
        migrations.AlterModelOptions(
            name='emailtypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='eventtypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genderlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='marketlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mediatypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='periodlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='phonetypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='relationshiplm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='repetitivetypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schooltypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='seriesdownloadlm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='seriesgenrelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='seriesstatelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='seriestypelm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='townlm',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AlterModelOptions(
            name='transactioncategorylm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transactiontypelm',
            options={'ordering': ['name']},
        ),
    ]
