# Generated by Django 3.1.2 on 2021-03-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0003_auto_20210103_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporationTypeLM',
        ),
    ]
