# Generated by Django 3.1.2 on 2021-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0004_delete_corporationtypelm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationTypeLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklaması')),
            ],
            options={
                'db_table': 'corporationtype_lm',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cardtypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='changepurposelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='citylm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='continentlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='countrylm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailtypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventtypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='genderlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mediatypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='periodlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonetypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationshiplm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repetitivetypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schooltypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seriesdownloadlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seriesgenrelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seriesstatelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seriestypelm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='townlm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactioncategorylm',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactiontypelm',
            name='user',
        ),
    ]
