# Generated by Django 3.2 on 2021-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0005_auto_20210413_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitivetypelm',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu'),
        ),
    ]
